### ISSUE TITLE
Use native singledispatch on Python 3.4

### ISSUE THREAD

**Issue by jayvdb** [vfaronov/httpolice#6]
singledispatch is a backport from Python 3.4, and shouldnt be needed on Python 3.4+.

**Comment by jayvdb** [comment]
Also I did some testing on Python 3.7, and the `singledispatch` backport fails its own tests on that version of Python.

Possibly it also fails on earlier versions of Python, as it is only supported on versions up to Python 3.3.

**Comment by vfaronov** [comment]
Thank you for the report. I think HTTPolice requires enum34 and singledispatch unconditionally just because somehow I couldn’t get the `python_version` markers to work as I wanted. Clearly this shouldn’t be a problem anymore. I will look into this when I get around to updating HTTPolice, hopefully within a couple months.
